version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      cache_from:
        - camondagster-app:latest
    user: vscode
    volumes:
      - ../:/workspaces/CamOnDagster:cached
    environment:
      - DLT_TELEMETRY=off
      - DBT_PROFILES_DIR=/workspaces/CamOnDagster/dbt
    working_dir: /workspaces/CamOnDagster
    networks:
      - dagster-net

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER="dagster"
      - POSTGRES_PASSWORD="dagster"
      - POSTGRES_DB="dagster"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -U 'dagster' -d 'dagster'"
      ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dagster-net

volumes:
  postgres_data:

networks:
  dagster-net:
    driver: bridge

