version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      cache_from:
        - camondagster-app:latest
    user: vscode
    volumes:
      - ../:/workspaces/CamOnDagster:cached
      - ./duckdb:/workspaces/CamOnDagster/duckdb:z
    environment:
      - DLT_TELEMETRY=off
      - DBT_PROFILES_DIR=/workspaces/CamOnDagster/dbt
    working_dir: /workspaces/CamOnDagster
    networks:
      - dagster-net

volumes:
  postgres_data:

networks:
  dagster-net:
    driver: bridge
