select id_meal as meal_id, str_meal as meal_name, str_category as category_name, str_area as country_name, 
str_instructions as instructions, str_meal_thumb as meal_image_url, str_youtube as meal_youtube_url, 
NULLIF(str_ingredient1, '') as str_ingredient1, 
NULLIF(str_ingredient2, '') as str_ingredient2,
NULLIF(str_ingredient3, '') as str_ingredient3,
NULLIF(str_ingredient4, '') as str_ingredient4,
NULLIF(str_ingredient5, '') as str_ingredient5,
NULLIF(str_ingredient6, '') as str_ingredient6,
NULLIF(str_ingredient7, '') as str_ingredient7, 
NULLIF(str_ingredient8, '') as str_ingredient8,
NULLIF(str_ingredient9, '') as str_ingredient9,
NULLIF(str_ingredient10, '') as str_ingredient10,
NULLIF(str_ingredient11, '') as str_ingredient11,
NULLIF(str_ingredient12, '') as str_ingredient12,
NULLIF(str_ingredient13, '') as str_ingredient13,
NULLIF(str_ingredient14, '') as str_ingredient14,
NULLIF(str_ingredient15, '') as str_ingredient15,
NULLIF(str_ingredient16, '') as str_ingredient16,
NULLIF(str_ingredient17, '') as str_ingredient17,
NULLIF(str_ingredient18, '') as str_ingredient18,
NULLIF(str_ingredient19, '') as str_ingredient19,
NULLIF(str_ingredient20, '') as str_ingredient20,
str_source as meal_url
    from {{ source("meals", "consumption") }} 