# name: Deploy dbt Docs (DuckDB)

# on:
#   push:
#     branches: [main]

# permissions:
#   contents: write

# jobs:
#   deploy-dbt-docs:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: 3.11

#       - name: Install dbt and DuckDB adapter
#         run: |
#           pip install dbt-duckdb

#       - name: Write dbt profiles.yml to file
#         run: |
#           mkdir -p ~/.dbt
#           echo "${{ secrets.DBT_PROFILES_YML }}" > ~/.dbt/profiles.yml

#       - name: Install dbt dependencies
#         run: |
#           cd dbt
#           dbt deps

#       - name: Create DuckDB folder if missing
#         run: |
#           cd dbt
#           mkdir -p duckdb

#       - name: Generate dbt docs
#         run: |
#           cd dbt
#           dbt docs generate
        
#       - name: List generated docs files
#         run: ls -l dbt/target
      
#       - name: Deploy docs to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v4
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: dbt/target
#           publish_branch: gh-pages